In [12]:
import pandas as pd
import numpy as np
from sklearn import preprocessing
import matplotlib.pyplot as plt 

from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn import metrics

In [13]:
data = pd.read_csv(r'D:\Projects\HIGGSBosonCOMP4730\Dataset\higgs2.csv', names=['lepton-pT', 'lepton-eta', 'lepton-phi', 'missing-energy-magnitude', 'missing-energy-phi', 'jet-1-pt', 'jet-1-eta', 'jet-1-phi', 'jet-1-b-tag', 'jet-2-pt', 'jet-2-eta', 'jet-2-phi', 'jet-2-b-tag', 'jet-3-pt', 'jet-3-eta', 'jet-3-phi', 'jet-3-b-tag', 'jet-4-pt', 'jet-4-eta', 'jet-4-phi', 'jet-4-b-tag', 'm_jj', 'm_jjj', 'm_lv', 'm_jlv', 'm_bb', 'm_wbb', 'm_wwbb'])

# data2 = pd.read_csv('higgs\HIGGS.csv')

In [14]:
print(data.head())

     lepton-pT  lepton-eta  lepton-phi  missing-energy-magnitude  \
1.0   0.748873   -0.874678   -1.194860                  0.766419   
0.0   1.630977    0.634973   -0.305970                  0.215144   
1.0   0.299586    1.489144    0.709529                  1.582114   
1.0   0.455144   -0.117904    1.524621                  0.991996   
1.0   0.540243   -0.597097   -0.997884                  0.668254   

     missing-energy-phi  jet-1-pt  jet-1-eta  jet-1-phi  jet-1-b-tag  \
1.0           -0.553490  0.394003   1.605137   0.657096     0.000000   
0.0           -0.452114  0.550285   0.697096  -1.597100     2.173076   
1.0           -1.352004  0.734232  -0.526828  -0.915218     2.173076   
1.0           -0.172513  2.414858  -1.634895  -1.567163     0.000000   
1.0            0.995326  0.583172  -0.925890   0.781276     0.000000   

     jet-2-pt  ...  jet-4-eta  jet-4-phi  jet-4-b-tag      m_jj     m_jjj  \
1.0  0.878681  ...  -1.674435   0.156879     0.000000  0.815718  1.086726   
0.0 

In [22]:
X = data.iloc[:, 0].values.reshape(-1, 1)
y = data.iloc[:, 0].values.reshape(-1, 1)

y_encode = preprocessing.LabelEncoder()
y_transformed = y_encode.fit_transform(y)

X_train, X_test, y_train, y_test = train_test_split(X, y_transformed, test_size= 0.3, random_state= 0)

lr = LogisticRegression()
lr.fit(X_train, y_train)

y_pred = lr.predict(X_test)
print('Accuracy of LR on test data: {:.2f}'.format(lr.score(X_test, y_test)))

C:\Users\ddaga\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\sklearn\preprocessing\_label.py:116: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


Accuracy of LR on test data: 0.00


In [21]:
from sklearn.metrics import confusion_matrix
confusion_matrix = confusion_matrix(y_test, y_pred)
print(confusion_matrix)

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 1]
 [0 0 0 ... 0 0 1]
 [0 0 0 ... 0 0 0]]
